ALTER TABLE activity_types ADD CONSTRAINT activity_types_name_key UNIQUE (name);
ALTER TABLE areas ADD CONSTRAINT areas_name_key UNIQUE (name);
ALTER TABLE bathroom_counts ADD CONSTRAINT bathroom_counts_name_key UNIQUE (name);
ALTER TABLE bedroom_counts ADD CONSTRAINT bedroom_counts_name_key UNIQUE (name);
ALTER TABLE client_statuses ADD CONSTRAINT client_statuses_name_key UNIQUE (name);
ALTER TABLE client_types ADD CONSTRAINT client_types_name_key UNIQUE (name);
ALTER TABLE coaching_flags ADD CONSTRAINT coaching_flags_flag_type_check CHECK ((flag_type = ANY (ARRAY['new_enquiry'::text, 'task'::text, 'needs_response'::text, 'missed'::text, 'notable_moment'::text, 'commitment'::text])));
ALTER TABLE coaching_memory ADD CONSTRAINT coaching_memory_contact_id_key UNIQUE (contact_id);
ALTER TABLE content_ideas ADD CONSTRAINT content_ideas_status_check CHECK ((status = ANY (ARRAY['new'::text, 'posted'::text, 'dismissed'::text])));
ALTER TABLE deal_priorities ADD CONSTRAINT deal_priorities_name_key UNIQUE (name);
ALTER TABLE deal_stages ADD CONSTRAINT deal_stages_category_check CHECK (((category)::text = ANY ((ARRAY['sale'::character varying, 'rental'::character varying])::text[])));
ALTER TABLE deal_types ADD CONSTRAINT deal_types_name_key UNIQUE (name);
ALTER TABLE developers ADD CONSTRAINT developers_name_key UNIQUE (name);
ALTER TABLE draft_responses ADD CONSTRAINT draft_responses_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'sent'::text, 'rejected'::text])));
ALTER TABLE enquiry_types ADD CONSTRAINT enquiry_types_name_key UNIQUE (name);
ALTER TABLE goals ADD CONSTRAINT goals_metric_check CHECK ((metric = ANY (ARRAY['deals_agreed'::text, 'deals_completed'::text, 'revenue'::text])));
ALTER TABLE goals ADD CONSTRAINT goals_period_type_check CHECK ((period_type = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annual'::text])));
ALTER TABLE goals ADD CONSTRAINT goals_period_type_period_start_metric_key UNIQUE (period_type, period_start, metric);
ALTER TABLE lead_sources ADD CONSTRAINT lead_sources_name_key UNIQUE (name);
ALTER TABLE lead_stages ADD CONSTRAINT lead_stages_name_key UNIQUE (name);
ALTER TABLE listing_statuses ADD CONSTRAINT listing_statuses_name_key UNIQUE (name);
ALTER TABLE newsletter_editions ADD CONSTRAINT newsletter_editions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'sent'::text])));
ALTER TABLE newsletter_transaction_stats ADD CONSTRAINT newsletter_transaction_stats_segment_check CHECK ((segment = ANY (ARRAY['off_plan'::text, 'ready'::text])));
ALTER TABLE progress_statuses ADD CONSTRAINT progress_statuses_name_key UNIQUE (name);
ALTER TABLE property_statuses ADD CONSTRAINT property_statuses_name_key UNIQUE (name);
ALTER TABLE property_types ADD CONSTRAINT property_types_name_key UNIQUE (name);
ALTER TABLE task_types ADD CONSTRAINT task_types_name_key UNIQUE (name);
ALTER TABLE users ADD CONSTRAINT users_auth_user_id_key UNIQUE (auth_user_id);
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE view_types ADD CONSTRAINT view_types_name_key UNIQUE (name);
ALTER TABLE whatsapp_contacts ADD CONSTRAINT whatsapp_contacts_match_status_check CHECK ((match_status = ANY (ARRAY['matched'::text, 'unmatched'::text, 'ambiguous'::text, 'self'::text])));
ALTER TABLE whatsapp_contacts ADD CONSTRAINT whatsapp_contacts_display_name_key UNIQUE (display_name);
ALTER TABLE whatsapp_conversations ADD CONSTRAINT whatsapp_conversations_contact_id_key UNIQUE (contact_id);
ALTER TABLE whatsapp_messages ADD CONSTRAINT whatsapp_messages_classification_check CHECK ((classification = ANY (ARRAY['new_enquiry'::text, 'task'::text, 'needs_response'::text, 'missed'::text, 'notable_moment'::text, 'fyi'::text])));
ALTER TABLE whatsapp_messages ADD CONSTRAINT whatsapp_messages_dedup_key UNIQUE (conversation_id, sender_name, sent_at_minute, body, dedup_seq);
