ALTER TABLE public.achievements ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);
ALTER TABLE public.activities ADD CONSTRAINT activities_pkey PRIMARY KEY (id);
ALTER TABLE public.activity_activity_types ADD CONSTRAINT activity_activity_types_pkey PRIMARY KEY (activity_id, activity_type_id);
ALTER TABLE public.activity_types ADD CONSTRAINT activity_types_pkey PRIMARY KEY (id);
ALTER TABLE public.areas ADD CONSTRAINT areas_pkey PRIMARY KEY (id);
ALTER TABLE public.bathroom_counts ADD CONSTRAINT bathroom_counts_pkey PRIMARY KEY (id);
ALTER TABLE public.bedroom_counts ADD CONSTRAINT bedroom_counts_pkey PRIMARY KEY (id);
ALTER TABLE public.client_client_statuses ADD CONSTRAINT client_client_statuses_pkey PRIMARY KEY (client_id, client_status_id);
ALTER TABLE public.client_client_types ADD CONSTRAINT client_client_types_pkey PRIMARY KEY (client_id, client_type_id);
ALTER TABLE public.client_statuses ADD CONSTRAINT client_statuses_pkey PRIMARY KEY (id);
ALTER TABLE public.client_types ADD CONSTRAINT client_types_pkey PRIMARY KEY (id);
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
ALTER TABLE public.coaching_flags ADD CONSTRAINT coaching_flags_pkey PRIMARY KEY (id);
ALTER TABLE public.coaching_memory ADD CONSTRAINT coaching_memory_pkey PRIMARY KEY (id);
ALTER TABLE public.content_ideas ADD CONSTRAINT content_ideas_pkey PRIMARY KEY (id);
ALTER TABLE public.deal_lead_stages ADD CONSTRAINT deal_lead_stages_pkey PRIMARY KEY (deal_id, lead_stage_id);
ALTER TABLE public.deal_priorities ADD CONSTRAINT deal_priorities_pkey PRIMARY KEY (id);
ALTER TABLE public.deal_stages ADD CONSTRAINT deal_stages_pkey PRIMARY KEY (id);
ALTER TABLE public.deal_types ADD CONSTRAINT deal_types_pkey PRIMARY KEY (id);
ALTER TABLE public.deals ADD CONSTRAINT deals_pkey PRIMARY KEY (id);
ALTER TABLE public.developers ADD CONSTRAINT developers_pkey PRIMARY KEY (id);
ALTER TABLE public.draft_responses ADD CONSTRAINT draft_responses_pkey PRIMARY KEY (id);
ALTER TABLE public.enquiries ADD CONSTRAINT enquiries_pkey PRIMARY KEY (id);
ALTER TABLE public.enquiry_areas ADD CONSTRAINT enquiry_areas_pkey PRIMARY KEY (enquiry_id, area_id);
ALTER TABLE public.enquiry_bathroom_counts ADD CONSTRAINT enquiry_bathroom_counts_pkey PRIMARY KEY (enquiry_id, bathroom_count_id);
ALTER TABLE public.enquiry_bedroom_counts ADD CONSTRAINT enquiry_bedroom_counts_pkey PRIMARY KEY (enquiry_id, bedroom_count_id);
ALTER TABLE public.enquiry_developers ADD CONSTRAINT enquiry_developers_pkey PRIMARY KEY (enquiry_id, developer_id);
ALTER TABLE public.enquiry_enquiry_types ADD CONSTRAINT enquiry_enquiry_types_pkey PRIMARY KEY (enquiry_id, enquiry_type_id);
ALTER TABLE public.enquiry_lead_stages ADD CONSTRAINT enquiry_lead_stages_pkey PRIMARY KEY (enquiry_id, lead_stage_id);
ALTER TABLE public.enquiry_property_statuses ADD CONSTRAINT enquiry_property_statuses_pkey PRIMARY KEY (enquiry_id, property_status_id);
ALTER TABLE public.enquiry_property_types ADD CONSTRAINT enquiry_property_types_pkey PRIMARY KEY (enquiry_id, property_type_id);
ALTER TABLE public.enquiry_types ADD CONSTRAINT enquiry_types_pkey PRIMARY KEY (id);
ALTER TABLE public.enquiry_view_types ADD CONSTRAINT enquiry_view_types_pkey PRIMARY KEY (enquiry_id, view_type_id);
ALTER TABLE public.goals ADD CONSTRAINT goals_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_sources ADD CONSTRAINT lead_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.lead_stages ADD CONSTRAINT lead_stages_pkey PRIMARY KEY (id);
ALTER TABLE public.listing_statuses ADD CONSTRAINT listing_statuses_pkey PRIMARY KEY (id);
ALTER TABLE public.newsletter_articles ADD CONSTRAINT newsletter_articles_pkey PRIMARY KEY (id);
ALTER TABLE public.newsletter_editions ADD CONSTRAINT newsletter_editions_pkey PRIMARY KEY (id);
ALTER TABLE public.newsletter_transaction_stats ADD CONSTRAINT newsletter_transaction_stats_pkey PRIMARY KEY (id);
ALTER TABLE public.offplan_calculation_rows ADD CONSTRAINT offplan_calculation_rows_pkey PRIMARY KEY (id);
ALTER TABLE public.offplan_calculations ADD CONSTRAINT offplan_calculations_pkey PRIMARY KEY (property_id);
ALTER TABLE public.progress_statuses ADD CONSTRAINT progress_statuses_pkey PRIMARY KEY (id);
ALTER TABLE public.properties ADD CONSTRAINT properties_pkey PRIMARY KEY (id);
ALTER TABLE public.property_areas ADD CONSTRAINT property_areas_pkey PRIMARY KEY (property_id, area_id);
ALTER TABLE public.property_bathroom_counts ADD CONSTRAINT property_bathroom_counts_pkey PRIMARY KEY (property_id, bathroom_count_id);
ALTER TABLE public.property_bedroom_counts ADD CONSTRAINT property_bedroom_counts_pkey PRIMARY KEY (property_id, bedroom_count_id);
ALTER TABLE public.property_developers ADD CONSTRAINT property_developers_pkey PRIMARY KEY (property_id, developer_id);
ALTER TABLE public.property_property_statuses ADD CONSTRAINT property_property_statuses_pkey PRIMARY KEY (property_id, property_status_id);
ALTER TABLE public.property_property_types ADD CONSTRAINT property_property_types_pkey PRIMARY KEY (property_id, property_type_id);
ALTER TABLE public.property_statuses ADD CONSTRAINT property_statuses_pkey PRIMARY KEY (id);
ALTER TABLE public.property_types ADD CONSTRAINT property_types_pkey PRIMARY KEY (id);
ALTER TABLE public.property_view_types ADD CONSTRAINT property_view_types_pkey PRIMARY KEY (property_id, view_type_id);
ALTER TABLE public.roi_calculations ADD CONSTRAINT roi_calculations_pkey PRIMARY KEY (property_id);
ALTER TABLE public.task_task_types ADD CONSTRAINT task_task_types_pkey PRIMARY KEY (task_id, task_type_id);
ALTER TABLE public.task_types ADD CONSTRAINT task_types_pkey PRIMARY KEY (id);
ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.uae_property_calculations ADD CONSTRAINT uae_property_calculations_pkey PRIMARY KEY (property_id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.view_types ADD CONSTRAINT view_types_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_contacts ADD CONSTRAINT whatsapp_contacts_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_conversations ADD CONSTRAINT whatsapp_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id);
