CREATE TABLE public.achievements (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, title text NOT NULL, description text, achieved_date date DEFAULT CURRENT_DATE NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.activities (id text NOT NULL, client_id text, activity_date date, notes text);
CREATE TABLE public.activity_activity_types (activity_id text NOT NULL, activity_type_id integer NOT NULL);
CREATE SEQUENCE public.activity_types_id_seq;
CREATE TABLE public.activity_types (id integer DEFAULT nextval('activity_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.activity_types_id_seq OWNED BY public.activity_types.id;
CREATE SEQUENCE public.areas_id_seq;
CREATE TABLE public.areas (id integer DEFAULT nextval('areas_id_seq'::regclass) NOT NULL, name character varying(100) NOT NULL, display_order integer);
ALTER SEQUENCE public.areas_id_seq OWNED BY public.areas.id;
CREATE SEQUENCE public.bathroom_counts_id_seq;
CREATE TABLE public.bathroom_counts (id integer DEFAULT nextval('bathroom_counts_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.bathroom_counts_id_seq OWNED BY public.bathroom_counts.id;
CREATE SEQUENCE public.bedroom_counts_id_seq;
CREATE TABLE public.bedroom_counts (id integer DEFAULT nextval('bedroom_counts_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.bedroom_counts_id_seq OWNED BY public.bedroom_counts.id;
CREATE TABLE public.client_client_statuses (client_id text NOT NULL, client_status_id integer NOT NULL);
CREATE TABLE public.client_client_types (client_id text NOT NULL, client_type_id integer NOT NULL);
CREATE SEQUENCE public.client_statuses_id_seq;
CREATE TABLE public.client_statuses (id integer DEFAULT nextval('client_statuses_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.client_statuses_id_seq OWNED BY public.client_statuses.id;
CREATE SEQUENCE public.client_types_id_seq;
CREATE TABLE public.client_types (id integer DEFAULT nextval('client_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.client_types_id_seq OWNED BY public.client_types.id;
CREATE TABLE public.clients (id text NOT NULL, name character varying(150) NOT NULL, phone character varying(50), email character varying(255), source_id integer, notes text, last_contact_date date, follow_up_date date, date_added date, date_of_birth date, personal_info text);
CREATE TABLE public.coaching_flags (id uuid DEFAULT gen_random_uuid() NOT NULL, message_id uuid NOT NULL, flag_type text NOT NULL, note text, resolved boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, suggested_resolved boolean DEFAULT false NOT NULL, due_date date);
CREATE TABLE public.coaching_memory (id uuid DEFAULT gen_random_uuid() NOT NULL, contact_id uuid NOT NULL, summary text NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.content_ideas (id uuid DEFAULT gen_random_uuid() NOT NULL, source_message_id uuid, idea text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, draft_copy text, status text DEFAULT 'new'::text NOT NULL, posted_at timestamp with time zone);
CREATE TABLE public.deal_lead_stages (deal_id text NOT NULL, lead_stage_id integer NOT NULL);
CREATE SEQUENCE public.deal_priorities_id_seq;
CREATE TABLE public.deal_priorities (id integer DEFAULT nextval('deal_priorities_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.deal_priorities_id_seq OWNED BY public.deal_priorities.id;
CREATE SEQUENCE public.deal_stages_id_seq;
CREATE TABLE public.deal_stages (id integer DEFAULT nextval('deal_stages_id_seq'::regclass) NOT NULL, name character varying NOT NULL, category character varying NOT NULL, display_order integer);
ALTER SEQUENCE public.deal_stages_id_seq OWNED BY public.deal_stages.id;
CREATE SEQUENCE public.deal_types_id_seq;
CREATE TABLE public.deal_types (id integer DEFAULT nextval('deal_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.deal_types_id_seq OWNED BY public.deal_types.id;
CREATE TABLE public.deals (id text NOT NULL, property_id text, owner_id text, buyer_id text, deal_type_id integer, value numeric, commission_percent numeric, commission_amount numeric, notes text, date_agreed date, date_completed date, deal_stage_id integer, commission_split_percent numeric, commission_split_amount numeric);
CREATE SEQUENCE public.developers_id_seq;
CREATE TABLE public.developers (id integer DEFAULT nextval('developers_id_seq'::regclass) NOT NULL, name character varying(100) NOT NULL, display_order integer);
ALTER SEQUENCE public.developers_id_seq OWNED BY public.developers.id;
CREATE TABLE public.draft_responses (id uuid DEFAULT gen_random_uuid() NOT NULL, conversation_id uuid NOT NULL, draft_text text NOT NULL, status text DEFAULT 'pending'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.enquiries (id text NOT NULL, client_id text, property_id text, notes text, building character varying(150), sqft numeric, floor character varying(20), completion_date date, budget numeric, enquiry_date date);
CREATE TABLE public.enquiry_areas (enquiry_id text NOT NULL, area_id integer NOT NULL);
CREATE TABLE public.enquiry_bathroom_counts (enquiry_id text NOT NULL, bathroom_count_id integer NOT NULL);
CREATE TABLE public.enquiry_bedroom_counts (enquiry_id text NOT NULL, bedroom_count_id integer NOT NULL);
CREATE TABLE public.enquiry_developers (enquiry_id text NOT NULL, developer_id integer NOT NULL);
CREATE TABLE public.enquiry_enquiry_types (enquiry_id text NOT NULL, enquiry_type_id integer NOT NULL);
CREATE TABLE public.enquiry_lead_stages (enquiry_id text NOT NULL, lead_stage_id integer NOT NULL);
CREATE TABLE public.enquiry_property_statuses (enquiry_id text NOT NULL, property_status_id integer NOT NULL);
CREATE TABLE public.enquiry_property_types (enquiry_id text NOT NULL, property_type_id integer NOT NULL);
CREATE SEQUENCE public.enquiry_types_id_seq;
CREATE TABLE public.enquiry_types (id integer DEFAULT nextval('enquiry_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.enquiry_types_id_seq OWNED BY public.enquiry_types.id;
CREATE TABLE public.enquiry_view_types (enquiry_id text NOT NULL, view_type_id integer NOT NULL);
CREATE TABLE public.goals (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, period_type text NOT NULL, period_start date NOT NULL, metric text NOT NULL, target_value numeric NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, group_id uuid);
CREATE SEQUENCE public.lead_sources_id_seq;
CREATE TABLE public.lead_sources (id integer DEFAULT nextval('lead_sources_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.lead_sources_id_seq OWNED BY public.lead_sources.id;
CREATE SEQUENCE public.lead_stages_id_seq;
CREATE TABLE public.lead_stages (id integer DEFAULT nextval('lead_stages_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.lead_stages_id_seq OWNED BY public.lead_stages.id;
CREATE TABLE public.listing_statuses (id integer GENERATED ALWAYS AS IDENTITY NOT NULL, name character varying NOT NULL, display_order integer);
CREATE TABLE public.newsletter_articles (id uuid DEFAULT gen_random_uuid() NOT NULL, edition_id uuid NOT NULL, headline text NOT NULL, summary text NOT NULL, source_name text NOT NULL, source_url text, display_order integer DEFAULT 0 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.newsletter_editions (id uuid DEFAULT gen_random_uuid() NOT NULL, period_label text NOT NULL, headline text, insights_text text, status text DEFAULT 'draft'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, luxury_sales_value_aed numeric, luxury_deal_count integer);
CREATE TABLE public.newsletter_transaction_stats (id uuid DEFAULT gen_random_uuid() NOT NULL, edition_id uuid NOT NULL, category text NOT NULL, segment text NOT NULL, value_aed numeric, share_pct numeric);
CREATE TABLE public.offplan_calculation_rows (id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, property_id text NOT NULL, "position" integer NOT NULL, milestone text NOT NULL, manual_label text, date text, pct text, paid text);
CREATE TABLE public.offplan_calculations (property_id text NOT NULL, inputs jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE SEQUENCE public.progress_statuses_id_seq;
CREATE TABLE public.progress_statuses (id integer DEFAULT nextval('progress_statuses_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.progress_statuses_id_seq OWNED BY public.progress_statuses.id;
CREATE TABLE public.properties (id text NOT NULL, owner_id text, notes text, building character varying(150), unit_number character varying(50), sqft numeric, service_charge numeric, floor character varying(20), rented_until date, completion_date date, rental_income numeric, asking_price numeric, op numeric, layout text, listing_status_id integer, last_update_sent_date date);
CREATE TABLE public.property_areas (property_id text NOT NULL, area_id integer NOT NULL);
CREATE TABLE public.property_bathroom_counts (property_id text NOT NULL, bathroom_count_id integer NOT NULL);
CREATE TABLE public.property_bedroom_counts (property_id text NOT NULL, bedroom_count_id integer NOT NULL);
CREATE TABLE public.property_developers (property_id text NOT NULL, developer_id integer NOT NULL);
CREATE TABLE public.property_property_statuses (property_id text NOT NULL, property_status_id integer NOT NULL);
CREATE TABLE public.property_property_types (property_id text NOT NULL, property_type_id integer NOT NULL);
CREATE SEQUENCE public.property_statuses_id_seq;
CREATE TABLE public.property_statuses (id integer DEFAULT nextval('property_statuses_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.property_statuses_id_seq OWNED BY public.property_statuses.id;
CREATE SEQUENCE public.property_types_id_seq;
CREATE TABLE public.property_types (id integer DEFAULT nextval('property_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.property_types_id_seq OWNED BY public.property_types.id;
CREATE TABLE public.property_view_types (property_id text NOT NULL, view_type_id integer NOT NULL);
CREATE TABLE public.roi_calculations (property_id text NOT NULL, inputs jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.task_task_types (task_id text NOT NULL, task_type_id integer NOT NULL);
CREATE SEQUENCE public.task_types_id_seq;
CREATE TABLE public.task_types (id integer DEFAULT nextval('task_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.task_types_id_seq OWNED BY public.task_types.id;
CREATE TABLE public.tasks (id text NOT NULL, client_id text, task_info text, entry_date date, deadline_date date, impact integer, effort integer, priority_score numeric, coaching_flag_id uuid);
CREATE TABLE public.uae_property_calculations (property_id text NOT NULL, inputs jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.users (id uuid DEFAULT gen_random_uuid() NOT NULL, auth_user_id uuid, email character varying(255) NOT NULL, full_name character varying(150), role character varying(50) DEFAULT 'agent'::character varying, is_active boolean DEFAULT true, last_login timestamp with time zone, created_at timestamp with time zone DEFAULT now());
CREATE SEQUENCE public.view_types_id_seq;
CREATE TABLE public.view_types (id integer DEFAULT nextval('view_types_id_seq'::regclass) NOT NULL, name character varying(50) NOT NULL, display_order integer);
ALTER SEQUENCE public.view_types_id_seq OWNED BY public.view_types.id;
CREATE TABLE public.whatsapp_contacts (id uuid DEFAULT gen_random_uuid() NOT NULL, display_name text NOT NULL, client_id text, match_status text DEFAULT 'unmatched'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.whatsapp_conversations (id uuid DEFAULT gen_random_uuid() NOT NULL, contact_id uuid, source_file text NOT NULL, imported_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.whatsapp_messages (id uuid DEFAULT gen_random_uuid() NOT NULL, conversation_id uuid NOT NULL, sender_name text NOT NULL, sent_at timestamp with time zone NOT NULL, body text, is_media boolean DEFAULT false NOT NULL, classification text, created_at timestamp with time zone DEFAULT now() NOT NULL, dedup_seq integer DEFAULT 1 NOT NULL, sent_at_minute timestamp with time zone GENERATED ALWAYS AS ((date_trunc('minute'::text, (sent_at AT TIME ZONE 'UTC'::text)) AT TIME ZONE 'UTC'::text)) STORED);
