ALTER TABLE activities ADD CONSTRAINT activities_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE activity_activity_types ADD CONSTRAINT activity_activity_types_activity_type_id_fkey FOREIGN KEY (activity_type_id) REFERENCES activity_types(id);
ALTER TABLE activity_activity_types ADD CONSTRAINT activity_activity_types_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE;
ALTER TABLE client_client_statuses ADD CONSTRAINT client_client_statuses_client_status_id_fkey FOREIGN KEY (client_status_id) REFERENCES client_statuses(id);
ALTER TABLE client_client_statuses ADD CONSTRAINT client_client_statuses_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE client_client_types ADD CONSTRAINT client_client_types_client_type_id_fkey FOREIGN KEY (client_type_id) REFERENCES client_types(id);
ALTER TABLE client_client_types ADD CONSTRAINT client_client_types_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE clients ADD CONSTRAINT clients_source_id_fkey FOREIGN KEY (source_id) REFERENCES lead_sources(id);
ALTER TABLE coaching_flags ADD CONSTRAINT coaching_flags_message_id_fkey FOREIGN KEY (message_id) REFERENCES whatsapp_messages(id);
ALTER TABLE coaching_memory ADD CONSTRAINT coaching_memory_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES whatsapp_contacts(id);
ALTER TABLE content_ideas ADD CONSTRAINT content_ideas_source_message_id_fkey FOREIGN KEY (source_message_id) REFERENCES whatsapp_messages(id);
ALTER TABLE deal_lead_stages ADD CONSTRAINT deal_lead_stages_lead_stage_id_fkey FOREIGN KEY (lead_stage_id) REFERENCES lead_stages(id);
ALTER TABLE deal_lead_stages ADD CONSTRAINT deal_lead_stages_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
ALTER TABLE deals ADD CONSTRAINT deals_deal_type_id_fkey FOREIGN KEY (deal_type_id) REFERENCES deal_types(id);
ALTER TABLE deals ADD CONSTRAINT deals_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id);
ALTER TABLE deals ADD CONSTRAINT deals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES clients(id);
ALTER TABLE deals ADD CONSTRAINT deals_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES clients(id);
ALTER TABLE deals ADD CONSTRAINT deals_deal_stage_id_fkey FOREIGN KEY (deal_stage_id) REFERENCES deal_stages(id);
ALTER TABLE draft_responses ADD CONSTRAINT draft_responses_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES whatsapp_conversations(id);
ALTER TABLE enquiries ADD CONSTRAINT enquiries_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id);
ALTER TABLE enquiries ADD CONSTRAINT enquiries_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE enquiry_areas ADD CONSTRAINT enquiry_areas_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_areas ADD CONSTRAINT enquiry_areas_area_id_fkey FOREIGN KEY (area_id) REFERENCES areas(id);
ALTER TABLE enquiry_bathroom_counts ADD CONSTRAINT enquiry_bathroom_counts_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_bathroom_counts ADD CONSTRAINT enquiry_bathroom_counts_bathroom_count_id_fkey FOREIGN KEY (bathroom_count_id) REFERENCES bathroom_counts(id);
ALTER TABLE enquiry_bedroom_counts ADD CONSTRAINT enquiry_bedroom_counts_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_bedroom_counts ADD CONSTRAINT enquiry_bedroom_counts_bedroom_count_id_fkey FOREIGN KEY (bedroom_count_id) REFERENCES bedroom_counts(id);
ALTER TABLE enquiry_developers ADD CONSTRAINT enquiry_developers_developer_id_fkey FOREIGN KEY (developer_id) REFERENCES developers(id);
ALTER TABLE enquiry_developers ADD CONSTRAINT enquiry_developers_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_enquiry_types ADD CONSTRAINT enquiry_enquiry_types_enquiry_type_id_fkey FOREIGN KEY (enquiry_type_id) REFERENCES enquiry_types(id);
ALTER TABLE enquiry_enquiry_types ADD CONSTRAINT enquiry_enquiry_types_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_lead_stages ADD CONSTRAINT enquiry_lead_stages_lead_stage_id_fkey FOREIGN KEY (lead_stage_id) REFERENCES lead_stages(id);
ALTER TABLE enquiry_lead_stages ADD CONSTRAINT enquiry_lead_stages_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_property_statuses ADD CONSTRAINT enquiry_property_statuses_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_property_statuses ADD CONSTRAINT enquiry_property_statuses_property_status_id_fkey FOREIGN KEY (property_status_id) REFERENCES property_statuses(id);
ALTER TABLE enquiry_property_types ADD CONSTRAINT enquiry_property_types_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_property_types ADD CONSTRAINT enquiry_property_types_property_type_id_fkey FOREIGN KEY (property_type_id) REFERENCES property_types(id);
ALTER TABLE enquiry_view_types ADD CONSTRAINT enquiry_view_types_enquiry_id_fkey FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE;
ALTER TABLE enquiry_view_types ADD CONSTRAINT enquiry_view_types_view_type_id_fkey FOREIGN KEY (view_type_id) REFERENCES view_types(id);
ALTER TABLE newsletter_articles ADD CONSTRAINT newsletter_articles_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES newsletter_editions(id) ON DELETE CASCADE;
ALTER TABLE newsletter_transaction_stats ADD CONSTRAINT newsletter_transaction_stats_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES newsletter_editions(id) ON DELETE CASCADE;
ALTER TABLE offplan_calculations ADD CONSTRAINT offplan_calculations_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE offplan_calculation_rows ADD CONSTRAINT offplan_calculation_rows_property_id_fkey FOREIGN KEY (property_id) REFERENCES offplan_calculations(property_id) ON DELETE CASCADE;
ALTER TABLE properties ADD CONSTRAINT properties_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES clients(id);
ALTER TABLE properties ADD CONSTRAINT properties_listing_status_id_fkey FOREIGN KEY (listing_status_id) REFERENCES listing_statuses(id);
ALTER TABLE property_areas ADD CONSTRAINT property_areas_area_id_fkey FOREIGN KEY (area_id) REFERENCES areas(id);
ALTER TABLE property_areas ADD CONSTRAINT property_areas_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_bathroom_counts ADD CONSTRAINT property_bathroom_counts_bathroom_count_id_fkey FOREIGN KEY (bathroom_count_id) REFERENCES bathroom_counts(id);
ALTER TABLE property_bathroom_counts ADD CONSTRAINT property_bathroom_counts_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_bedroom_counts ADD CONSTRAINT property_bedroom_counts_bedroom_count_id_fkey FOREIGN KEY (bedroom_count_id) REFERENCES bedroom_counts(id);
ALTER TABLE property_bedroom_counts ADD CONSTRAINT property_bedroom_counts_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_developers ADD CONSTRAINT property_developers_developer_id_fkey FOREIGN KEY (developer_id) REFERENCES developers(id);
ALTER TABLE property_developers ADD CONSTRAINT property_developers_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_property_statuses ADD CONSTRAINT property_property_statuses_property_status_id_fkey FOREIGN KEY (property_status_id) REFERENCES property_statuses(id);
ALTER TABLE property_property_statuses ADD CONSTRAINT property_property_statuses_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_property_types ADD CONSTRAINT property_property_types_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE property_property_types ADD CONSTRAINT property_property_types_property_type_id_fkey FOREIGN KEY (property_type_id) REFERENCES property_types(id);
ALTER TABLE property_view_types ADD CONSTRAINT property_view_types_view_type_id_fkey FOREIGN KEY (view_type_id) REFERENCES view_types(id);
ALTER TABLE property_view_types ADD CONSTRAINT property_view_types_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE roi_calculations ADD CONSTRAINT roi_calculations_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE task_task_types ADD CONSTRAINT task_task_types_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;
ALTER TABLE task_task_types ADD CONSTRAINT task_task_types_task_type_id_fkey FOREIGN KEY (task_type_id) REFERENCES task_types(id);
ALTER TABLE tasks ADD CONSTRAINT tasks_coaching_flag_id_fkey FOREIGN KEY (coaching_flag_id) REFERENCES coaching_flags(id);
ALTER TABLE tasks ADD CONSTRAINT tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE uae_property_calculations ADD CONSTRAINT uae_property_calculations_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE whatsapp_contacts ADD CONSTRAINT whatsapp_contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE whatsapp_conversations ADD CONSTRAINT whatsapp_conversations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES whatsapp_contacts(id);
ALTER TABLE whatsapp_messages ADD CONSTRAINT whatsapp_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES whatsapp_conversations(id);
